### PR TITLE
v1.28.21

### LINKED ISSUE #1504: Hover Element block and JavaScript Code block do not work in iframe multi-level nesting
**Describe the bug**
Hover Element block and JavaScript Code block do not work in iframe multi-level nesting

and Debug mode automatically turns on at runtime

**To Reproduce**

**Expected behavior**

**Screenshots**
image
image
image

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser: [e.g. Google Chrome]
 - Extension Version: [e.g. v1.28.18]

**Additional context**

### LINKED ISSUE #1507: Scroll Element Not Working
**Describe the bug**

**To Reproduce**
1. Go to url of twitter (X) post
2. Delay 5000
3. Scroll down 
4. Delay 5000

**Expected behavior**

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: 1.28.19

**Additional context**

### LINKED ISSUE #1516: The execution of automasetvariable in the ExecuteWorkflow block does not save data to storage
The execution of automasetvariable in the ExecuteWorkflow block does not save data to storage. $$has been added, but I see this value change in the variables console, but when workflow stops, the value changes back to its original value.

### PR DESCRIPTION
**Pull request by Kholid060**
### Bug fixes
- Fix scroll element block (https://github.com/AutomaApp/automa/commit/8955de573e22d201f48077627ac6d428d0bd1c3d), close #1507
- Fix storage variable value not updated in the execute workflow block (https://github.com/AutomaApp/automa/commit/e49509a8f5acf58188b748c753b612a56307db67), close #1516
- Fix javascript block not working in nested iframe (https://github.com/AutomaApp/automa/commit/6741c8af340ed7ca25a6274d47e36db2c038e34f), close #1504 
- Fix variable storage name (https://github.com/AutomaApp/automa/pull/1522/commits/7f540017a447700eeaf07a9ac62019ca3d9bc4b0)

### CODE REVIEW

File: src/workflowEngine/WorkflowWorker.js [hunk 1]
```diff
@@ -119,9 +121,18 @@ class WorkflowWorker {
...
       vars[varName].push(value);
+      variableName = varName;
+    } else {
+      vars[name] = value;
+    }
+
+    if (variableName.startsWith('$$')) {
+      dbStorage.variables.put({
+        value,
+        name: variableName,
```
Comment (UnluckyNinja) [inline src/workflowEngine/WorkflowWorker.js:132]: My workflow keeps running repeatedly while it should be once per day (by checking variables in workflow). Then I found in Storage tab, the variables are prefixed with duplicated "$$". So, I guess this is the cause.

In previous code, the variable's name was sliced: https://github.com/AutomaApp/automa/pull/1522/files#diff-e2be43c3a6d1b35564d0d2980d83866ffef90cca2e66eded0a5ac7b47db31a08L509

Comment (Kholid060) [reply src/workflowEngine/WorkflowWorker.js:132]: You're right, will fix in the next update
